// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtzpmagcgyzngezgdxxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0enBtYWdjZ3l6bmdlemdkeHhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NTYwOTcsImV4cCI6MjA3MzAzMjA5N30.Ru3SfDnY5pXm38dRuI6i2io6dkLxPTZN8PCFmWyXugU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});